### ISSUE TITLE
Implementation of a custom table

### ISSUE THREAD

**Issue by lecssmi** [gerardnico/calcite#1]
In CalciteFrameworksTest.java, the built-in ReflectiveSchema is used. Can  you replace it with a custom table and schema, such as Mongo table?

**Comment by lecssmi** [comment]
And is there any detailed information on how to use calcite? 
 Thanks!

**Comment by gerardnico** [comment]
The whole available documentation is on their website.
https://calcite.apache.org/docs/

They have also a mongo adapter :)
https://calcite.apache.org/docs/howto.html#mongodb-adapter

This repository is the result of my own research.

Implementing another table is just a question of replacing the output of the ReflectiveSchema by your own.
